import type { KittyConfig } from './config';

export const DEFAULT_CONFIG: KittyConfig = {
  theme: {
    id: 'default-dark',
    name: 'Default Dark',
    foreground: '#cdd6f4',
    background: '#1e1e2e',
    cursor: '#f5e0dc',
    cursorTextColor: '#1e1e2e',
    selectionBackground: '#45475a',
    selectionForeground: '#cdd6f4',
    palette: {
      color0: '#45475a',
      color1: '#f38ba8',
      color2: '#a6e3a1',
      color3: '#f9e2af',
      color4: '#89b4fa',
      color5: '#f5c2e7',
      color6: '#94e2d5',
      color7: '#bac2de',
      color8: '#585b70',
      color9: '#f38ba8',
      color10: '#a6e3a1',
      color11: '#f9e2af',
      color12: '#89b4fa',
      color13: '#f5c2e7',
      color14: '#94e2d5',
      color15: '#a6adc8',
    },
  },
  font: {
    family: 'JetBrains Mono',
    size: 13,
    lineHeight: 1.0,
    letterSpacing: 0,
    disableLigatures: false,
  },
  keybindings: [],
  window: {
    padding: { top: 12, right: 12, bottom: 12, left: 12 },
    opacity: 1.0,
    blur: 0,
    decorations: true,
    resizeStrategy: 'simple',
    confirmOSWindowClose: true,
  },
  tabBar: {
    style: 'fade',
    position: 'top',
    maxTitleLength: 100,
    activityBell: true,
    activeFontStyle: 'bold',
  },
  layouts: {
    enabledLayouts: ['tall', 'fat', 'grid', 'splits'],
  },
  mouse: {
    hideMouseWhenTyping: true,
    mouseHideWait: 3,
    focusFollowsMouse: false,
    pointerShapeWhenGrabbed: 'arrow',
    defaultPointerShape: 'arrow',
  },
  scrollback: {
    lines: 2000,
    fillEnum: 'default',
    inSecondaryScreen: false,
  },
  performance: {
    repaintDelay: 10,
    syncToMonitor: true,
  },
  customEntries: [],
};
